project_doc_fallback_filenames = ["CLAUDE.md", "AGENTS.md"]
log_user_prompt = false

codex_home = "@paiBasePath@/codex"

instructions = '''
  Go read @@paiBasePath@/claude/skills/CORE/SKILL.md for base instructions. Then acknowledge you've read this by saying, "@assistantName@ setup complete." 
'''

[model_providers.ollama]
name = "ollama"
base_url = "@ollamaHost@/v1"

[shell_environment_policy]
inherit = "none"
set = { PATH = "@paiBasePath@/bin:@paiEnvPath@:$PATH", MY_FLAG = "1" }
ignore_default_excludes = false
exclude = ["AWS_*", "AZURE_*", "GCP_*"]

[features]
web_search_request = true
skills = true

[history]
persistence = "none"

[tui]
animations = true
